### ISSUE TITLE
Modal onsave

### ISSUE THREAD

**Issue by iamwyza** [dagnelies/ractive-bootstrap#2]
It would be nice if for modals instead of onclick={{onsave}} it would be on-click={{onsave}}.  Then the event propagation will bubble up to the parent for observation.

**Comment by dagnelies** [comment]
I agree. At the time this library was made, custom events were not available in ractive. (See  https://github.com/ractivejs/ractive/issues/1684)
Meanwhile there is support for it in edge:
https://github.com/ractivejs/ractive/pull/2095
But since this is supposed to work with latest, it's postponed. You're welcome to make an edge branch if you like though.
